/** Tunable thresholds + circuit-breaker defaults (design §3 / §7.2). */

export const BATCH_ACT_ABOVE = 0.8;
export const BATCH_REVIEW_ABOVE = 0.5;

export const CATEGORY_ACT_ABOVE = 0.8;
export const CATEGORY_REVIEW_ABOVE = 0.5;

export const SPAM_ACT_ABOVE = 0.75;
export const SPAM_REVIEW_ABOVE = 0.4;

export const URGENT_ACT_ABOVE = 0.8;
export const URGENT_REVIEW_ABOVE = 0.5;

export const NEEDS_HUMAN_ACT_ABOVE = 0.8;
export const NEEDS_HUMAN_REVIEW_ABOVE = 0.5;

export const AUTO_ACT_ABOVE = 0.7;
export const AUTO_REVIEW_ABOVE = 0.5;

/** Per-call timeout for the live System One request (design §7.2). */
export const JEV_TIMEOUT_MS = 5_000;

/** Trip after this many failures inside the failure window. */
export const CIRCUIT_FAILURE_THRESHOLD = 5;
/** Sliding window that counts consecutive/clustered failures. */
export const CIRCUIT_FAILURE_WINDOW_MS = 60_000;
/** Skip live Jev for this long after the breaker trips. */
export const CIRCUIT_COOLDOWN_MS = 30_000;

export const STATE_BODY_MAX_CHARS = 4_000;

export const CATEGORY_OPTIONS = {
  billing: 'Payments, invoices, refunds, or being charged incorrectly.',
  support:
    'A help request, bug report, or technical problem that needs troubleshooting.',
  sales:
    'Buying interest, a quote request, a demo request, or pricing questions.',
  otp: 'A one-time verification code, a sign-in/sign-up confirmation link, or an account confirmation code.',
  newsletter:
    'A recurring newsletter, bulk marketing, or promotional broadcast, not addressed to the recipient personally.',
  other:
    "Personal correspondence or anything that doesn't clearly fit the categories above.",
} as const;

export type CategoryId = keyof typeof CATEGORY_OPTIONS;

export const CATEGORY_LABELS = [
  'billing',
  'support',
  'sales',
  'otp',
  'newsletter',
] as const satisfies readonly Exclude<CategoryId, 'other'>[];

export const QUESTION_CATEGORY =
  'What is this email primarily about?';
export const QUESTION_SPAM =
  'Is this email spam, a phishing attempt, or an unsolicited scam?';
export const YES_SPAM =
  'This is spam, phishing, or a scam attempt and should not be treated as legitimate correspondence.';
export const NO_SPAM =
  'This is legitimate correspondence, even if it is a newsletter, receipt, or automated notification.';

export const QUESTION_URGENT =
  'Does the sender convey urgency, expecting a fast response — an active problem, a time-sensitive request, or an explicit deadline?';
export const YES_URGENT =
  'The sender is asking for or clearly expects a prompt response.';
export const NO_URGENT =
  'There is no indication the sender expects a fast response.';

export const QUESTION_NEEDS_HUMAN =
  "Does replying to or acting on this email require a human's judgment or authority, rather than something an automated agent can safely resolve on its own?";
export const YES_NEEDS_HUMAN =
  "A human should review this before any reply or action is taken — e.g. it involves a financial decision, a policy judgment, a complaint, or something with real consequences if handled wrong.";
export const NO_NEEDS_HUMAN =
  "An automated agent can safely read, file, or reply to this without a human's involvement.";

export const QUESTION_AUTO =
  "Is this an automatic reply, bounce/delivery-failure notice, or out-of-office notification — an automated response to something that was sent to the sender's address — rather than a message a person or system deliberately composed and sent with new content?";
export const YES_AUTO =
  'This is an automatic reply-type notification (out-of-office, bounce, delivery failure, auto-acknowledgment).';
export const NO_AUTO =
  'This is a deliberately composed message with its own content, even if it was generated by an automated system (e.g. a receipt, a verification code, or a newsletter) rather than typed by a human.';
